import tkinter as tk


window = tk.Tk()
window.title('Choose the Best Hosiptal For You')
##window.geometry('1050x700')

def pop_window():
    tk.messagebox.showinfo('Your best hospital','The best hospital for you : \n XX医院 \n XXX医院 \n XXXX医院 \n XXXXX医院 \n XXXXXX医院 \n XXXXXXX医院')

gs = ('Gill Sans', 16)

title = tk.Label(window, text='Choose the Best Hosiptal For You', font=('Gill Sans', 24))
main = tk.Frame(window)
submit = tk.Button(text='Submit', width=15, command = pop_window)

left = tk.Frame(main)
right = tk.Frame(main)

a0 = tk.Label(left, text='Choose Your Disease', bg='#eee', font=gs)
a1 = tk.Label(left, text='Age', bg='#eee', font=gs)
a2 = tk.Label(left, text='BMI', bg='#eee', font=gs)
a3 = tk.Label(left, text='Stage of Disease', bg='#eee', font=gs)
a4 = tk.Label(left, text='Annual Income / $', bg='#eee', font=gs)
a5 = tk.Label(left, text='Functional Status', bg='#eee', font=gs)
a6 = tk.Label(left, text='Sex', bg='#eee', font=gs)
a7 = tk.Label(left, text='Smoker', bg='#eee', font=gs)
a8 = tk.Label(left, text='Education level', bg='#eee', font=gs)
a9 = tk.Label(left, text='Race', bg='#eee', font=gs)

s0 = tk.StringVar()
s6 = tk.StringVar()
s7 = tk.StringVar()
s8 = tk.StringVar()
s9 = tk.StringVar()

w0 = tk.OptionMenu(left, s0, 'Myocardial infarction')
w1 = tk.Scale(left, from_=0, to=120, orient=tk.HORIZONTAL, length=300, showvalue=True, tickinterval=30)
w2 = tk.Scale(left, from_=15, to=35, orient=tk.HORIZONTAL, length=300, showvalue=True, tickinterval=5, resolution=0.1)
w3 = tk.Scale(left, from_=0, to=100, orient=tk.HORIZONTAL, length=300, showvalue=False)
w4 = tk.Scale(left, from_=0, to=1000000, orient=tk.HORIZONTAL, length=300, showvalue=False)
w5 = tk.Scale(left, from_=0, to=100, orient=tk.HORIZONTAL, length=300, showvalue=False)
w6 = tk.OptionMenu(left, s6, 'Male', 'Female')
w7 = tk.OptionMenu(left, s7, 'Yes', "No")
w8 = tk.OptionMenu(left, s8, 'None', 'Primary School', 'Junior High', 'Senior High', 'Graduate', 'Post Graduate')
w9 = tk.OptionMenu(left, s9, 'African American')

w0.config(width=20)
w6.config(width=20)
w7.config(width=20)
w8.config(width=20)
w9.config(width=20)

l3 = tk.Label(left, text='Early', width=20, bg='#bfb', font=gs)
l4 = tk.Label(left, text='$ 80000 / year', width=20, bg='#bfb', font=gs)
l5 = tk.Label(left, text='Partially Independent', width=20, bg='#bfb', font=gs)

b0 = tk.Label(right, text='Comorbidity', bg='#eee', font=gs)
b1 = tk.Checkbutton(right, text='Myocardial Infarct')
b2 = tk.Checkbutton(right, text='Congestive Heart Failure')
b3 = tk.Checkbutton(right, text='Peripheral Vascular Disease')
b4 = tk.Checkbutton(right, text='Dementia')
b5 = tk.Checkbutton(right, text='Cerebrovascular Disease')
b6 = tk.Checkbutton(right, text='Chronic Lung Disease')
b7 = tk.Checkbutton(right, text='Connective Tissue Disease')
b8 = tk.Checkbutton(right, text='Ulcer')
b9 = tk.Checkbutton(right, text='Chronic liver disease')
b10 = tk.Checkbutton(right, text='Diabetes')
b11 = tk.Checkbutton(right, text='Hemiplegia')
b12 = tk.Checkbutton(right, text='Moderate or Severe Kidney Disease')
b13 = tk.Checkbutton(right, text='Diabetes with End Organ Damage')
b14 = tk.Checkbutton(right, text='Leukemia')
b15 = tk.Checkbutton(right, text='Lymphoma')
b16 = tk.Checkbutton(right, text='Moderate or Severe Liver Disease')
b17 = tk.Checkbutton(right, text='Malignant Tumor')
b18 = tk.Checkbutton(right, text='Metastasis')
b19 = tk.Checkbutton(right, text='AIDs')


title.grid(row=1, column=1, pady=10)
main.grid(row=2, column=1, pady=20)
submit.grid(row=3, column=1)

left.grid(row=1, column=1, padx=20)
right.grid(row=1, column=2, padx=20)

a0.grid(row=1, column=1, padx=20, pady=10)
a1.grid(row=2, column=1, padx=20, pady=10)
a2.grid(row=3, column=1, padx=20, pady=10)
a3.grid(row=4, column=1, padx=20, pady=10)
a4.grid(row=5, column=1, padx=20, pady=10)
a5.grid(row=6, column=1, padx=20, pady=10)
a6.grid(row=7, column=1, padx=20, pady=10)
a7.grid(row=8, column=1, padx=20, pady=10)
a8.grid(row=9, column=1, padx=20, pady=10)
a9.grid(row=10, column=1, padx=20, pady=10)

w0.grid(row=1, column=2, padx=20, pady=10)
w1.grid(row=2, column=2, padx=20, pady=10)
w2.grid(row=3, column=2, padx=20, pady=10)
w3.grid(row=4, column=2, padx=20, pady=10)
w4.grid(row=5, column=2, padx=20, pady=10)
w5.grid(row=6, column=2, padx=20, pady=10)
w6.grid(row=7, column=2, padx=20, pady=10)
w7.grid(row=8, column=2, padx=20, pady=10)
w8.grid(row=9, column=2, padx=20, pady=10)
w9.grid(row=10, column=2, padx=20, pady=10)

l3.grid(row=4, column=3)
l4.grid(row=5, column=3)
l5.grid(row=6, column=3)

b0.grid(row=1, column=1, sticky=tk.W)
b1.grid(row=2, column=1, sticky=tk.W)
b2.grid(row=3, column=1, sticky=tk.W)
b3.grid(row=4, column=1, sticky=tk.W)
b4.grid(row=5, column=1, sticky=tk.W)
b5.grid(row=6, column=1, sticky=tk.W)
b6.grid(row=7, column=1, sticky=tk.W)
b7.grid(row=8, column=1, sticky=tk.W)
b8.grid(row=9, column=1, sticky=tk.W)
b9.grid(row=10, column=1, sticky=tk.W)
b10.grid(row=11, column=1, sticky=tk.W)
b11.grid(row=12, column=1, sticky=tk.W)
b12.grid(row=13, column=1, sticky=tk.W)
b13.grid(row=14, column=1, sticky=tk.W)
b14.grid(row=15, column=1, sticky=tk.W)
b15.grid(row=16, column=1, sticky=tk.W)
b16.grid(row=17, column=1, sticky=tk.W)
b17.grid(row=18, column=1, sticky=tk.W)
b18.grid(row=19, column=1, sticky=tk.W)
b19.grid(row=20, column=1, sticky=tk.W)


window.mainloop()
